#pragma once

#include <bell/pitches.h>

#define NOTE_DURATION 50 //ms

const note_t DEFAULT_CHIME[] = {
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7,
        NOTE_D7, NOTE_FS7, NOTE_A7
};

const note_t DEBUG_CHIME[] = {
        NOTE_A4, NOTE_A4, NOTE_A4,
        NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE,
        NOTE_A4, NOTE_A4, NOTE_A4
};

const note_t MEGALOVANIA[] = {
        NOTE_D7, NOTE_D7, NOTE_D7, NOTE_PAUSE,
        NOTE_D7, NOTE_D7, NOTE_D7, NOTE_PAUSE,
        NOTE_D8, NOTE_D8, NOTE_D8, NOTE_D8,
        NOTE_D8, NOTE_D8, NOTE_PAUSE, NOTE_PAUSE,
        NOTE_A7, NOTE_A7, NOTE_A7, NOTE_A7, 
        NOTE_A7, NOTE_A7, NOTE_PAUSE, NOTE_PAUSE,
        NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE, 
        NOTE_GS7, NOTE_GS7, NOTE_GS7, NOTE_GS7, 
        NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE, 
        NOTE_G7, NOTE_G7, NOTE_G7, NOTE_G7, 
        NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE, NOTE_PAUSE, 
        NOTE_F7, NOTE_F7, NOTE_F7, NOTE_F7, 
        NOTE_F7, NOTE_F7, NOTE_F7, NOTE_PAUSE,
        NOTE_D7, NOTE_D7, NOTE_D7, NOTE_PAUSE,
        NOTE_F7, NOTE_F7, NOTE_F7, NOTE_PAUSE,
        NOTE_G7, NOTE_G7, NOTE_G7
};

#define MELODY_LEN(MELODY) (sizeof(MELODY) / sizeof(note_t))
