TU-DO Wireless Doorbell: WiFiHandler Class Reference
WiFiHandler Class Reference
WiFihandler class.
#include <WiFiHandler.h>
Public Types
enum wifi_stat { UNINITIALIZED, DISCONNECTED, CONNECTING, CONNECTED }
Public Member Functions
WiFiHandler ()
Default constructor.
WiFiHandler (const String ssid, const String psk, const IPAddress ip, const IPAddress gateway, const IPAddress subnet, const uint16_t timeout_s, const bool rejoin=true)
Constructor.
void connect ()
Connects to the WiFi network.
void disconnect ()
Disconnects from WiFi.
void update ()
Updates the state machine.
wifi_stat status ()
Returns the current state of the state machine.
Private Member Functions
bool timeout ()
Returns if the connection attempt has timed out.
void _connect ()
Connects to the WiFi network.
void unexpected_disconnect ()
Reports unexpected WiFi disconnects.
Private Attributes
String ssid
String psk
IPAddress ip
IPAddress gateway
IPAddress subnet
uint16_t timeout_ms
bool rejoin
wifi_stat stat = DISCONNECTED
unsigned long timeout_tstamp
Detailed Description
WiFihandler class.
The WiFiHandler class provides a simple interface for connecting to a WiFi network, as well as checking the connection status.
The ESP8266WiFi library is used for the actual WiFi connection and the state machine simply wraps around the WiFi object.
Definition at line 42 of file WiFiHandler.h.
Constructor & Destructor Documentation
WiFiHandler() [1/2]
WiFiHandler::WiFiHandler ()
Default constructor.
The default constructor only serves to allow the class to be declared without immidiately initializing it. This spares us from having to allocate the object on the heap via a pointer, which we generally want to avoid on embedded systems.
Definition at line 34 of file WiFiHandler.cpp.
WiFiHandler() [2/2]
WiFiHandler::WiFiHandler (const String ssid, const String psk, const IPAddress ip, const IPAddress gateway, const IPAddress subnet, const uint16_t timeout_s, const bool rejoin = true)
Constructor.
Parameters
ssid The SSID of the WiFi network to connect to
psk The PSK of the WiFi network to connect to
ip The IP address to assign to the ESP8266
gateway The gateway to assign to the ESP8266
subnet The subnet to assign to the ESP8266
timeout_ms The timeout in milliseconds for the connection attempt (0 = No/Infinite timeout)
rejoin If true, the ESP8266 will attempt to reconnect automatically after unexpected disconnects
Definition at line 40 of file WiFiHandler.cpp.
References log_msg().
Member Function Documentation
_connect()
void WiFiHandler::_connect () private
Connects to the WiFi network.
The following function begins the WiFi object without setting a timeout.
Once called, the state machine is set to the CONNECTING state.
Once the connection is established, the state machine is set to the CONNECTED state.
Definition at line 52 of file WiFiHandler.cpp.
References log_msg().
Referenced by connect(), and update().
connect()
void WiFiHandler::connect ()
Connects to the WiFi network.
The following function should be called to connect to the WiFi network.
Once called, the begin() method of the WiFi object is called and the state machine is set to the CONNECTING state.
Once the connection is established, the state machine is set to the CONNECTED state.
If a timeout has been set and a connection could not be established until the timeout has expired, the state machine is set to the DISCONNECTED.
Definition at line 73 of file WiFiHandler.cpp.
References _connect().
disconnect()
void WiFiHandler::disconnect ()
Disconnects from WiFi.
The following function disconnects from the WiFi network and sets the state machine to the DISCONNECTED
Definition at line 99 of file WiFiHandler.cpp.
References log_msg().
Referenced by unexpected_disconnect(), and update().
status()
WiFiHandler::wifi_stat WiFiHandler::status ()
Returns the current state of the state machine.
The following function returns the current state
Possible states are: UNINITIALIZED: The object has not been initialized (ie. only the default constructor has been called) DISCONNECTED: The device is disconnected from the WiFi network CONNECTING: The device is attempting to connect to the WiFi network CONNECTED: The device is connected to the WiFi network
Use this method to check the connection status.
Returns
The current state of the state machine
Definition at line 167 of file WiFiHandler.cpp.
unexpected_disconnect()
void WiFiHandler::unexpected_disconnect () private
Reports unexpected WiFi disconnects.
The following function reports unexpected WiFi disconnects. Once called, the state machine is set to the DISCONNECTED state.
If the rejoin flag is set true, the WiFi object's will disconnect() method not not be called, and a reconnect will be attempted automatically
If the rejoing flag is set false, the function redirects to the disconnect() function, which will not attempt to automatically re-establish a connection.
Definition at line 82 of file WiFiHandler.cpp.
References disconnect(), and log_msg().
Referenced by update().
update()
void WiFiHandler::update ()
Updates the state machine.
The following function updates the state machine and must be called periodically.
Definition at line 119 of file WiFiHandler.cpp.
References _connect(), disconnect(), log_msg(), timeout(), and unexpected_disconnect().
The documentation for this class was generated from the following files:
include/common/WiFiHandler.h
src/common/WiFiHandler.cpp