TU-DO Wireless Doorbell: StatusLED Class Reference
StatusLED Class Reference
StatusLED class.
#include <StatusLED.h>
Public Types
enum led_mode { OFF, ON, BLINK, BLINK_INV }
Possible LED states.
Public Member Functions
StatusLED ()
Default constructor.
StatusLED (uint8_t pin, unsigned long blink_interval=500)
Constructor.
void setBlinkInterval (unsigned long interval)
Sets the LEDs blink interval in milliseconds.
void mode (led_mode m)
Sets the LEDs mode.
led_mode getMode ()
Gets the LEDs mode.
void update ()
Updates the LEDs state.
unsigned int blinks ()
Counts how many times the LED has blinked.
Private Attributes
uint8_t pin
bool stat
led_mode mod
unsigned long blink_interval
unsigned long tstamp
unsigned int blks
Detailed Description
StatusLED class.
The StatusLED class provides a simple "asynchronous" interface for controlling status LEDs. LEDs can be set to blink, be on or off. In order to work "asynchronously", the class requires the user to continously the update() method.
Definition at line 36 of file StatusLED.h.
Member Enumeration Documentation
led_mode
enum StatusLED::led_mode
Possible LED states.
Enumerator
OFF
Constantly off.
ON
Constantly on.
BLINK
First ON then OFF.
BLINK_INV
First OFF then ON.
Definition at line 39 of file StatusLED.h.
Constructor & Destructor Documentation
StatusLED() [1/2]
StatusLED::StatusLED ()
Default constructor.
The default constructor only serves to allow the class to be declared without immidiately initializing it. This spares us from having to allocate the object on the heap via a pointer, which we generally want to avoid on embedded systems.
Definition at line 36 of file StatusLED.cpp.
StatusLED() [2/2]
StatusLED::StatusLED (uint8_t pin, unsigned long blink_interval = 500)
Constructor.
The constructor initializes the StatusLED object with the given pin and blink interval.
The blink interval defines the time between two consecutive LED state changes if the LED is set to blink.
Parameters
pin The pin to which the LED is connected
blink_interval The blink interval in milliseconds (default: 500)
Definition at line 41 of file StatusLED.cpp.
References log_msg(), mode(), OFF, and setBlinkInterval().
Member Function Documentation
blinks()
unsigned int StatusLED::blinks ()
Counts how many times the LED has blinked.
The blinkCount() method returns the number of times the LED has blinked since it was set to blink.
Returns
The number of times the LED has blinked
Definition at line 106 of file StatusLED.cpp.
getMode()
StatusLED::led_mode StatusLED::getMode ()
Gets the LEDs mode.
Returns
The LEDs mode
Definition at line 87 of file StatusLED.cpp.
mode()
void StatusLED::mode (led_mode m)
Sets the LEDs mode.
The following function sets the LEDs mode. Available modes are:
OFF LED is off
ON LED is on
BLINK LED blinks ON, then OFF
BLINK_INV LED blinks OFF, then ON
The BLINK_INV mode is useful for alternating blinks between two LEDs.
Parameters
mode The LEDs mode
Definition at line 56 of file StatusLED.cpp.
References BLINK, BLINK_INV, log_msg(), OFF, and ON.
Referenced by StatusLED().
update()
void StatusLED::update ()
Updates the LEDs state.
The update() method must be called continously in order to update the LEDs state. This is necessary to make the LEDs blink "asynchronously".
Definition at line 93 of file StatusLED.cpp.
References BLINK.
The documentation for this class was generated from the following files:
include/common/StatusLED.h
src/common/StatusLED.cpp