TU-DO Wireless Doorbell: include/common/log.h File Reference
log.h File Reference
Provides functions and macros for logging.
#include <Arduino.h>
Macros
#define DBG_LOG(CATEGORY, MSG)
Functions
void log_msg (String category, String message)
Outputs a log message to the serial port.
Detailed Description
Provides functions and macros for logging.
Author
Patrick Pedersen, TU-DO Makerspace
Definition in file log.h.
Macro Definition Documentation
DBG_LOG
#define DBG_LOG (CATEGORY, MSG)
Outputs a log message to the serial port on debug builds only
Definition at line 41 of file log.h.
Function Documentation
log_msg()
void log_msg (String category, String message)
Outputs a log message to the serial port.
Parameters
category The category of the log message
message The log message
Definition at line 32 of file log.cpp.
Referenced by WiFiHandler::_connect(), WiFiHandler::disconnect(), FALLBACK_ERROR(), StatusLED::mode(), StatusLED::StatusLED(), WiFiHandler::unexpected_disconnect(), WiFiHandler::update(), and WiFiHandler::WiFiHandler().